# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: grcharle <grcharle@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/29 11:55:25 by grcharle          #+#    #+#              #
#    Updated: 2025/11/06 19:47:15 by grcharle         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# .SILENT directive to make execution quieter
# .SILENT:

# Phony targets declaration
# .PHONY: all clean fclean re bonus

# Default goal
.DEFAULT_GOAL := all

# Compiler and flags
CC := cc
CFLAGS := -Wall -Wextra -Werror -pedantic -MMD
CPPFLAGS := -I.
LDFLAGS := 
LDLIBS :=

# Project names
NAME := philo
# BONUS_NAME := libfunctions_bonus.a

# Directory setup
OBJECTS_DIR := .objects
# BONUS_DIR := .bonus_objects

# Safe removal command
RM := rm -f

# Sources
SOURCES_MANDATORY := main.c
# SOURCES_BONUS := ft_bonus.c ft_extra.c ft_special.c

# OBJECTS_MANDATORY := $(patsubst %.c,\
# 	$(OBJECTS_DIR)/%.o,\
# 	$(addprefix philo/, $(SOURCES_MANDATORY))\
# )

# Method 1: Combine and transform with directory prefixes
# OBJECTS_MANDATORY := $(patsubst %.c,\
# 	$(OBJECTS_DIR)/%.o,\
# 	$(addprefix philo/, $(SOURCES_MANDATORY))\
# )
OBJECTS_MANDATORY := \
	$(addprefix \
		$(OBJECTS_DIR)/, \
		$(SOURCES_MANDATORY:.c=.o)\
	)
# OBJECTS_BONUS := $(addprefix $(BONUS_DIR)/, $(SOURCES_BONUS:.c=.o))

# Combine all objects if needed for cleanup or other operations
ALL_OBJECTS := $(OBJECTS_MANDATORY)

# Dependency files (automatically generated by -MMD)
DEPS_MANDATORY := $(OBJECTS_MANDATORY:.o=.d)
# DEPS_BONUS := $(OBJECTS_BONUS:.o=.d)

# Include dependency files
-include $(DEPS_MANDATORY)

# Create directories if they don't exist
$(OBJECTS_DIR):
	mkdir -p $@

# $(BONUS_DIR):
# 	mkdir -p $@

# Compilation rules
$(OBJECTS_DIR)/%.o: %.c | $(OBJECTS_DIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
	echo "Compiled $< → $@"

# Archive creation
$(NAME): $(OBJECTS_MANDATORY)
	$(AR) rcs $@ $^
	echo "Created $(NAME) with: $(SOURCES_MANDATORY)"

# Main targets
all: $(NAME)

# Cleanup rules
clean:
	$(RM) -r $(OBJECTS_DIR)
	$(RM) $(DEPS_MANDATORY)
	echo "Cleaned object files and dependencies"

fclean: clean
	$(RM) $(NAME)
	echo "Full clean completed"

# re: fclean all

# # Security enhancements
# .SECONDARY: $(OBJECTS_MANDATORY) $(OBJECTS_BONUS)
# .PRECIOUS: $(OBJECTS_DIR) $(BONUS_DIR)

# # Info target for debugging
# info:
# 	echo "Mandatory sources: $(SOURCES_MANDATORY)"
# 	echo "Bonus sources: $(SOURCES_BONUS)"
# 	echo "Mandatory objects: $(OBJECTS_MANDATORY)"
# 	echo "Bonus objects: $(OBJECTS_BONUS)"
# 	echo "All objects: $(ALL_OBJECTS)"










# .DEFAULT_GOAL := all

# CC := cc
# CFLAGS := -Wall -Wextra -Werror -pedantic
# CPPFLAGS := -I.

# # Specifies options for the linker:
# # example: -L/usr/local/lib
# LDFLAGS :=

# # Lists libraries to link with:
# # example: -lm -lpthread
# LDLIBS :=

# NAME := philo
# NAME_BONUS := philo_bonus

# OBJECTS_DIR := .objects

# RM := rm -f

# SOURCES_MANDATORY := main.c

# SOURCES_BONUS :=

# OBJECTS_MANDATORY := $(patsubst %.c,\
# 	$(OBJECTS_DIR)/%.o,\
# 	$(addprefix philo/, $(SOURCES_MANDATORY))\
# )
# OBJECTS_BONUS := $(patsubst %.c,\
# 	$(OBJECTS_DIR)/%.o,\
# 	$(SOURCES_BONUS)\
# )

# DEPS_MANDATORY := $(OBJECTS_MANDATORY:.o=.d)
# DEPS_BONUS := $(OBJECTS_BONUS:.o=.d)

# -include $(DEPS_MANDATORY) $(DEPS_BONUS)

# $(OBJECTS_DIR): mkdir -p $@/$(NAME)

# $(OBJECTS_DIR)/%.o: %.c | $(OBJECTS_DIR)
# 	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@ $(LDLIBS)

# $(NAME): $(OBJECTS_MANDATORY)

# $(NAME_BONUS): $(OBJECTS_BONUS)

# all: $(NAME)

# bonus: $(NAME_BONUS)

# clean:
# 	$(RM) $(OBJECTS_MANDATORY) $(OBJECTS_BONUS)
# 	$(RM) $(DEPS_MANDATORY) $(DEPS_BONUS)
# 	$(RM) -r $(OBJECTS_DIR)

# fclean: clean
# # 	$(RM) -v $(NAME)
# # 	$(RM) -v $(NAME_BONUS)

# re: fclean all

# info:
# 	echo -e "Mandatory objects: $(OBJECTS_MANDATORY)"
# 	echo -e "Bonus objects: $(OBJECTS_BONUS)"
# 	echo -e "Mandatory dependencies: $(DEPS_MANDATORY)"
# 	echo -e "Bonus dependencies: $(DEPS_BONUS)"
#  	echo -e "CFLAGS: $(CFLAGS)"
# 	echo -e "CPPFLAGS: $(CPPFLAGS)"

# norm:
# 	norminette -R .

# .SECONDARY: $(OBJECTS_MANDATORY) $(OBJECTS_BONUS)

# .PRECIOUS: $(OBJECTS_DIR)

# # .SILENT:

# # .PHONY: all clean fclean re bonus
